"""
System prompts for each agent in the Multi-Agent Virtual Company.

Each agent has specialized prompts that define their role and behavior.
"""

from .researcher import (
    RESEARCHER_SYSTEM_PROMPT,
    RESEARCHER_TASK_PROMPT,
    RESEARCHER_SEARCH_PROMPT,
)
from .analyst import (
    ANALYST_SYSTEM_PROMPT,
    ANALYST_TASK_PROMPT,
    ANALYST_REVISION_PROMPT,
)
from .critic import (
    CRITIC_SYSTEM_PROMPT,
    CRITIC_TASK_PROMPT,
    CRITIC_ITERATION_WARNING,
)
from .writer import (
    WRITER_SYSTEM_PROMPT,
    WRITER_TASK_PROMPT,
    WRITER_QUICK_REPORT_PROMPT,
)
from .supervisor import (
    SUPERVISOR_SYSTEM_PROMPT,
    SUPERVISOR_ROUTING_PROMPT,
    SUPERVISOR_ERROR_PROMPT,
)

__all__ = [
    "RESEARCHER_SYSTEM_PROMPT",
    "RESEARCHER_TASK_PROMPT",
    "RESEARCHER_SEARCH_PROMPT",
    "ANALYST_SYSTEM_PROMPT",
    "ANALYST_TASK_PROMPT",
    "ANALYST_REVISION_PROMPT",
    "CRITIC_SYSTEM_PROMPT",
    "CRITIC_TASK_PROMPT",
    "CRITIC_ITERATION_WARNING",
    "WRITER_SYSTEM_PROMPT",
    "WRITER_TASK_PROMPT",
    "WRITER_QUICK_REPORT_PROMPT",
    "SUPERVISOR_SYSTEM_PROMPT",
    "SUPERVISOR_ROUTING_PROMPT",
    "SUPERVISOR_ERROR_PROMPT",
]
